services:
  db_ngcash_test:
    image: postgres
    container_name: db_ngcash_test
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 2345:5432
    env_file:
      - .env.test

  back_end_app_test:
    container_name: back_end_app_test
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db_ngcash_test
    env_file:
      - .env.test
    command: bash -c "npm run test:migration:run && npm test"
